module: Siesta
version: 1.0.0
author: Andreas Grosam
github_url: https://github.com/couchdeveloper/futurelib
readme: README.md
output: docs/html
xcodebuild_arguments: [-scheme,FutureLib-MacOS,-target,FutureLib-MacOS]
swift_version: 2.2
clean: true
skip_undocumented: true
