language: objective-c

branches:
 only:
 - master

xcode_workspace: FutureLib.xcworkspace
osx_image: xcode7.2

script:
- rake clean
- xcodebuild test -workspace FutureLib.xcworkspace -scheme FutureLib-MacOS -destination 'arch=x86_64'| xcpretty
- xcodebuild test -workspace FutureLib.xcworkspace -scheme FutureLib-iOS -destination 'platform=iOS Simulator,name=iPhone 6' test | xcpretty
- xcodebuild test -workspace FutureLib.xcworkspace -scheme FutureLib-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p' test | xcpretty
- xcodebuild build -workspace FutureLib.xcworkspace -scheme FutureLib-watchOS -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm' | xcpretty
